import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Hiring Platform",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <header className="bg-white border-b border-[#e0e0e0] px-6 py-4 flex justify-between items-center">
                <h1 className="text-2xl font-semibold text-[#1d1f20]">Job List</h1>
                <div className="w-10 h-10 rounded-full bg-gradient-to-br from-[#01959f] to-[#43936c] flex items-center justify-center text-white font-semibold">
                    A
                </div>
            </header>
            {children}
        </>
    );
}
