import type { Metadata } from "next";
import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Hiring Platform",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            {children}
        </>
    );
}
